<?php
/**
 * @file
 * Expand menu items and set active-trail according to the current path
 */

/**
 * Implement hook_init
 * Add Trail By Path checkbox to menu_block block configure page
 */
function menu_trail_by_path_init() {
  
  $parent_candidates_alias = _get_parent_candidates(drupal_get_path_alias());
  // don't even bother if current page is root
  if (empty($parent_candidates_alias)) {
    return;
  }
  
  // convert alias path to normal drupal system path
  $parent_candidates = array();
  foreach ($parent_candidates_alias as $alias_path) {
    // change alias to drupal system path
    $parent_candidates[] = drupal_get_normal_path($alias_path);
  }
  
  // get the deepest menu item in each menu
  // Todo: translate db_query() into db_select()
  $result = db_query("SELECT m1.menu_name, m1.link_path FROM {menu_links} m1 INNER JOIN (SELECT menu_name, MAX(depth) AS max_depth FROM {menu_links} WHERE link_path IN (:candidates) GROUP BY menu_name) d1 ON m1.menu_name = d1.menu_name AND m1.depth = d1.max_depth WHERE m1.link_path IN (:candidates)", array(':candidates'=>$parent_candidates));
  
  // set the active-trail for each menu found
  foreach ($result as $record) {
    menu_tree_set_path($record->menu_name, $record->link_path);
  }
  
  // Todo: Fix Breadcrumbs as well.
  
}

/**
 * Return an array of candidate paths
 * e.g. for a path 'foo/bar/zee' 
 * candidates are 'foo/bar/zee', 'foo/bar', 'foo'
 */
function _get_parent_candidates($path = NULL) {
  if ($path == NULL) {
    $path = request_path();
  }
  $pieces = explode('/', $path);
  $path = '';
  $parent_candidates = array();
  foreach ($pieces as $piece) {
    $path .= $piece . '/';
    array_unshift($parent_candidates, rtrim($path, '/'));
  }
  return $parent_candidates;
}